services:
  frontend:
    image: ${FRONTEND_IMAGE}:${IMAGE_TAG}
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    image: ${BACKEND_IMAGE}:$IMAGE_TAG}
    env_file:
      - .env
    ports:
      - "${BACKEND_PORT}:8000"
    depends_on:
      - database
    restart: unless-stopped

  database:
    image: postgres:15
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: