# This is a basic workflow to help you get started with Actions

name: Deploy Conduit Application

on:
  push:
    branches:
      - c-deployment

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        # hier eingefügt
      - name: Check image variables
        run: |
          echo "BACKEND_IMAGE=${{ vars.BACKEND_IMAGE }}"
          echo "FRONTEND_IMAGE=${{ vars.FRONTEND_IMAGE }}"
          echo "IMAGE_TAG=${{ vars.IMAGE_TAG }}"
# Ende

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./Backend
          push: true
          tags: ghcr.io/erikogeek/conduit-backend:latest

      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./Frontend
          push: true
          tags: ghcr.io/erikogeek/conduit-frontend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}

          key: ----BEGIN OPENSSH PRIVATE KEY-----
            b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
            QyNTUxOQAAACAxNWNhH+N7I8Uiq3xijp61vFlbWW7l8HivR4/mB89aSgAAAKiJlYtsiZWL
            bAAAAAtzc2gtZWQyNTUxOQAAACAxNWNhH+N7I8Uiq3xijp61vFlbWW7l8HivR4/mB89aSg
            AAAEBESeg/9kulc/PLdTO6vJSk+ab/Ev5uEQie5JbYawkhPjE1Y2Ef43sjxSKrfGKOnrW8
            WVtZbuXweK9Hj+YHz1pKAAAAIWdpdGh1Yi1hY3Rpb25zLWNvbmR1aXQtZGVwbG95bWVudA
            ECAwQ=
            -----END OPENSSH PRIVATE KEY-----


          # ${{ secrets.SSH_PRIVATE_KEY }}

          script: |
            cd ~/Conduit-Deployment
            docker compose pull
            docker compose up -d